language: python
python:
  - 3.7
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
  - pip install coveralls

install:
  - python setup.py install

script:
  - coverage run -m unittest  discover tests
  - python -m coveralls
